config/routes.rb
Rails.application.routes.draw do
  get 'visitor_logs/new'
  get 'sessions/new'
  resources :users
  resources :visitor_logs

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
   get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'signout'  => 'visitor_logs#sign_out'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :visitor_logs
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, presence: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end


  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/models/visitor_log.rb
class VisitorLog < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      @visitor_log = current_user.visitor_logs.last
      if !@visitor_log.nil?&&@visitor_log.time_out.nil?
        redirect_to current_user.visitor_logs.last
      else
        redirect_to visitor_logs_new_path
      end

    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	# debugger
  end
  def new
  	@user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
    	flash[:success] = "Welcome to the Sample App!"
      redirect_to visitor_logs_new_path
    else
      render 'new'
    end
  end 
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/controllers/visitor_logs_controller.rb
class VisitorLogsController < ApplicationController
  def new
    @visitor_log = VisitorLog.new
  end

  def create
    @visitor_log = VisitorLog.new(visitor_log_params)
    timeIn = Time.now.getlocal
    @visitor_log.time_in=timeIn
    @visitor_log.student_name=current_user.name
    @visitor_log.user_id=current_user.id
    if @visitor_log.save
      flash[:success] = "You have started logging your hours"
      redirect_to @visitor_log
    else
      render 'new'
    end
  end

  def show
    @visitor_log = VisitorLog.find(params[:id])

  end

  def sign_out
    @visitor_log =current_user.visitor_logs.last
    timeOut = Time.now.getlocal
    @visitor_log.time_out = timeOut
    @visitor_log.save
    redirect_to visitor_logs_path
  end

  def index
    @visitor_logs= current_user.visitor_logs
  end

end

private

def visitor_log_params
  params.require(:visitor_log).permit(:reason)
end

app/helpers/application_helper.rb
module ApplicationHelper
	  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
# Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

# Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # checks if admin
  def admin

  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
 # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/visitor_logs_helper.rb
module VisitorLogsHelper
  def signed_in?
    if logged_in?
      @visitor_log = current_user.visitor_logs.last
      !@visitor_log.nil?&&@visitor_log.time_out.nil?
    end
  end
  def current_log
    if logged_in?
      current_user.visitor_logs.last
    end
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Volunteer Log", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">

        <% if logged_in? %>
            <% if signed_in?%>
                <li><%= link_to "Sign out", current_log, method: "get" %></li>
            <%else%>
                <li><%= link_to "Sign In", visitor_logs_new_path, method: "get" %></li>
            <%end%>
            <li><%= link_to "Logs", visitor_logs_path%></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>


        <% else %>
            <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim'%>
  </head>
  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

    <h1>About</h1>
    <p>
      The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
      Tutorial</em></a> is a
      <a href="http://www.railstutorial.org/book">book</a> and
      <a href="http://screencasts.railstutorial.org/">screencast series</a>
      to teach web development with
      <a href="http://rubyonrails.org/">Ruby on Rails</a>.
      This is the sample application for the tutorial.
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/#help">Rails Tutorial help
      section</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Welcome to the Volunteer Log</h1>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>

app/views/visitor_logs/index.html.erb
<div class = "container">
  <h1>Past Logs</h1>
  <table class="table table-hover">
    <tr>
      <th>Date</th>
      <th>Time Started</th>
      <th>Time Ended</th>
      <th>Reason</th>
    </tr>
    <% @visitor_logs.reverse.each do |visitor_log| %>
        <% if visitor_log.time_out.nil?%>
    <tr class = "warning">
      <%else%>
            <tr>
              <%end%>
      <td><%=visitor_log.time_in.strftime("%m-%d-%Y ")%></td>
      <td><%=visitor_log.time_in.strftime("%H:%M ")%></td>
      <% if visitor_log.time_out.nil?%>
            <td>In Progress</td>
          <%else%>
          <td><%=visitor_log.time_out.strftime("%H:%M ")%></td>
          <%end%>
      <td><%=visitor_log.reason%></td>
    </tr>
    <%end%>
  </table>

</div>

app/views/visitor_logs/new.html.erb
<% provide(:title, 'Log') %>
<h1>Log</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@visitor_log) do |f| %>
        <%= f.label :reason %>
        <%= f.text_area :reason, class: 'form-control' %>

        <%= f.submit "Log", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/visitor_logs/show.html.erb
<div class = "container center">
<h1>Session in Progress</h1>

<h2 style="color:red">Start Time: <%=@visitor_log.time_in.strftime("%H:%M %p")%></h2>

<h2>You're currently signed in. Click here to sign out.</h2>

  <%=link_to "Sign Out" ,signout_path%>


</div>

app/views/visitor_logs/sign_out.html.erb
kmoma